In [ ]:
import pandas as pd
import numpy as np

clean = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/clean.csv', na_values=["nan", "NaN", "N/A", "None", "null"]).replace(np.nan, 0).astype(int)
dirty = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/dirty.csv', na_values=["nan", "NaN", "N/A", "None", "null"]).replace(np.nan, 0).astype(int)


# dirty.head()
error_df = clean != dirty
print(error_df.sum(axis=0))
print(error_df.sum().sum() / (clean.shape[0] * clean.shape[1]))
print(clean.shape)
cnt = 0
for r in range(len(clean)):
    if error_df.iloc[r].sum() == 0:
        cnt += 1
print(cnt)
print(1 - cnt / len(clean))



# if error_sum_df[0] > 20:
#     print('ye')
# print(clean.columns[1])

Cont1     5306
Cont2     2077
Cont3     5446
Cont4     1827
Cont5     5403
Cont6     3642
Cont7     5426
Cont8     5416
Cont9     3572
Cont10    5379
dtype: int64
0.09998620689655173
(43500, 10)
15020
0.654712643678161

In [21]:
dirty = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/dirty.csv', na_values=["nan", "NaN", "N/A", "None", "null"])
dirty_partition = dirty.iloc[:40]
dirty_partition.head()

   Cont1  Cont2  Cont3  Cont4  Cont5  Cont6  Cont7  Cont8  Cont9  Cont10
0   50.0   21.0   77.0    0.0   28.0    0.0   27.0   48.0   22.0     2.0
1   55.0    0.0   92.0    NaN    0.0   26.0    NaN   92.0   56.0     4.0
2   53.0    0.0   82.0    0.0   52.0   -5.0   29.0   30.0    2.0     NaN
3    NaN    0.0   76.0    0.0   28.0   18.0   40.0   48.0    8.0     1.0
4   37.0    0.0    NaN    0.0   34.0  -26.0   43.0   46.0    2.0     NaN

In [22]:
dirty_partition = dirty_partition.astype('Int64')
print(dirty_partition)

    Cont1  Cont2  Cont3  Cont4  Cont5  Cont6  Cont7  Cont8  Cont9  Cont10
0      50     21     77      0     28      0     27     48     22       2
1      55      0     92   <NA>      0     26   <NA>     92     56       4
2      53      0     82      0     52     -5     29     30      2    <NA>
3    <NA>      0     76      0     28     18     40     48      8       1
4      37      0   <NA>      0     34    -26     43     46      2    <NA>
5      85      0     88     -4      6      1      3     83     80    <NA>
6      56   <NA>     81      0     -4     11     25     86     62       4
7      55     -1   <NA>     -3   <NA>     -4     40     41      2       1
8      53   <NA>     77      0     28      0     23     48     24       4
9      37      0    101   <NA>     28      0     64     73      8       1
10     37      0     78     -2     12      0     42     65     24    <NA>
11     45      0     84      0     46     20     38     37      0       1
12     38      2   <NA>      0     38      7     39     38      0       1
13     37      0     78      0     -2      5     41     81   <NA>       1
14     41      0    100      0     38     -8     59     61      2       1
15     41      0     89      1     38    -16     48     50   <NA>    <NA>
16   <NA>      0     85     -2     46     -4     38     39   <NA>       1
17     49      0     79   <NA>     46     -5     30     32      2    <NA>
18   <NA>   <NA>     82   <NA>     50      4     33     33      0    <NA>
19     37   <NA>    105     -2     36     -4     68     69      0       1
20     44      3     77      0     44      2     33     33      0       1
21    106      2    108      0     70      0      1     38     36       5
22     37     -5     76      0     28      0     40   <NA>      8       1
23     49      0   <NA>      0     50   <NA>     52     51      0       1
24     45   <NA>     87     -2     44     -4     43     43      0       1
25     37      4     80      0     -2      0     43     83   <NA>    <NA>
26     55     -1     98      0     52      8     42     46   <NA>       4
27     55      0     86      8   <NA>      0     31     32      0       1
28   <NA>      3     88      3     54      0     32     33      2       1
29     37   <NA>     74      0     26     -1     38     48     10       1
30     37      0    106      0     36      3     68     69      2       1
31     49      0    107   <NA>     46    -16     58     60      2       1
32     79   <NA>     83      0    -46      0      4    130    126       5
33     51      0     79      0     52     29     28     27      0       1
34     59      4     84   <NA>     60     24   <NA>     24      0       1
35     37      0    108      0     30   <NA>     71     77      6       1
36     56      3   <NA>      0     46      9     41     51     10       4
37     39   <NA>   <NA>      0   <NA>   <NA>     37     38      0       1
38     51     -5     81      0     52      0     30     30      0       1
39     49      0   <NA>   <NA>     46     -9     29     31      2       1

In [37]:
dirty = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/dirty.csv', na_values=["nan", "NaN", "N/A", "None", "null"]).astype('Int64').astype(str)
dirty.head()
dirty.to_csv('/data1/qianc/EMCL/datasets/shuttle/dirty_2.csv', index=False)

In [42]:
clean = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/clean.csv', na_values=["nan", "NaN", "N/A", "None", "null"], dtype='str').replace(np.nan, '')
dirty = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/dirty.csv', na_values=["nan", "NaN", "N/A", "None", "null"], dtype='str').replace(np.nan, '')

error_df = clean != dirty
print(error_df.sum(axis=0))
print(error_df.sum().sum() / (clean.shape[0] * clean.shape[1]))
print(clean.shape)
cnt = 0
for r in range(len(clean)):
    if error_df.iloc[r].sum() == 0:
        cnt += 1
print(cnt)
print(1 - cnt / len(clean))

Cont1     5306
Cont2     5524
Cont3     5446
Cont4     5382
Cont5     5474
Cont6     5376
Cont7     5426
Cont8     5416
Cont9     5401
Cont10    5379
dtype: int64
0.1244367816091954
(43500, 10)
11507
0.7354712643678161

In [26]:
print(dirty.iloc[0])
print(clean.iloc[0])

Cont1     50.0
Cont2     21.0
Cont3     77.0
Cont4      0.0
Cont5     28.0
Cont6      0.0
Cont7     27.0
Cont8     48.0
Cont9     22.0
Cont10     2.0
Name: 0, dtype: object
Cont1     50
Cont2     21
Cont3     77
Cont4      0
Cont5     28
Cont6      0
Cont7     27
Cont8     48
Cont9     22
Cont10     2
Name: 0, dtype: object

In [41]:
dirty = pd.read_csv('/data1/qianc/EMCL/datasets/shuttle/dirty_2.csv', na_values=["nan", "NaN", "N/A", "None", "null"], dtype='str').replace(np.nan, '')
dirty.head()

  Cont1 Cont2 Cont3 Cont4 Cont5 Cont6 Cont7 Cont8 Cont9 Cont10
0    50    21    77     0    28     0    27    48    22      2
1    55     0    92           0    26          92    56      4
2    53     0    82     0    52    -5    29    30     2
3           0    76     0    28    18    40    48     8      1
4    37     0           0    34   -26    43    46     2